language: python
python:
  - "2.7"
  - "3.5"
addons:
  postgresql: "9.4"
services:
  - postgresql
install:
  - "pip install -e ."
  - "pip install -r requirements-dev.txt
script:
  - flake8 .
  - py.test --ds=seed_control_interface_service.testsettings */tests.py
